version: '2'
services:
  maps:
    build:
      context: .
      args:
        USER: docker
    image: game-cluster
    environment:
       MONGO_HOST: mongo
       HOST_NAME: maps.rabbits
    depends_on:
      - mongo
    volumes:
      - ../:/app
    working_dir: /app
    networks:
      default:
        aliases:
          - maps.rabbits
  mongo:
    image: mongo:3.3
    command: --smallfiles
    networks:
      default:
        aliases:
          - mongo.rabbits
  dns:
    image: andyshinn/dnsmasq
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/udp
      - 53:53/tcp
    command: --max-cache-ttl=30 --max-ttl=30
networks:
  default:
    driver: bridge
